recipes-core/systemd/systemd_%.bbappend

This lets systemd allow lingering for the ceres user.
Asteroid-launcher will start on boot and will continue running without login sessions.

Fix lingering for ceres

---

recipes-nemomobile/nemo-qml-plugins/nemo-qml-plugin-contextkit_git.bb

Git repository changed upstream:
ERROR: Fetcher failure: Fetch command failed with exit code 128, output:
Cloning into bare repository '/home/asteroid/workspace/asteroid-image-bass/build/downloads/git2/git.merproject.org.mer-core.nemo-qml-plugin-contextkit.git'...
fatal: could not read Username for 'https://git.merproject.org': No such device or address
ERROR: Function failed: Fetcher failure for URL: 'git://git.merproject.org/mer-core/nemo-qml-plugin-contextkit.git;protocol=https'. Unable to fetch URL from any source.

Point contextkit to the mer-core-attic

---

classes/asteroid-image.bbclass
recipes-asteroid/asteroid-calendar/asteroid-calendar_git.bb
recipes-asteroid/asteroid-settings/asteroid-settings_git.bb
recipes-asteroid/supported-languages/supported-languages/locale.conf
recipes-asteroid/supported-languages/supported-languages/localeEnv.conf
recipes-asteroid/supported-languages/supported-languages_git.bb

Adds global i18n support and builds the translations for the settings app. Currently non-functional. DO NOT MERGE.
In my idea, this should make i18n work. It at least puts all the files on the right spot with the correct rights. Unfortunately, after building and testing this, I got the following error on my device when trying to launch any app: `lipstick[850]: wl_event_loop_dispatch error: -1`. Why this happens is beyond me.
The build script also returns 2 QA warnings:
```
WARNING: QA Issue: python-pygobject: /python-pygobject/usr/lib/python2.7/site-packages/pygtk.pth is owned by uid 1000, which is the same as the user running bitbake. This may be due to host contamination [host-user-contaminated]
WARNING: QA Issue: asteroid-launcher: …
```

Add i18n support

---

recipes-asteroid/asteroid-alarmclock/asteroid-alarmclock_git.bb
recipes-asteroid/asteroid-settings/asteroid-settings_git.bb

lrelease seems unable to read wildcards in a .pro file, so we directly
tell it to just translate all translations
As per documentation on http://linuxcommand.org/man_pages/lrelease1.html.
This means the TRANSLATIONS entry in the .pro files are unnecessary.

Fix building languages

---

recipes-nemomobile/sensorfw/sensorfw_git.bb

Before this change I got a failure:
```
| /home/dlan/local/src/asteroid/build/tmp-glibc/sysroots/x86_64-linux/usr/libexec/arm-oe-linux-gnueabi/gcc/arm-oe-linux-gnueabi/6.2.0/ld: warning: library search path "/usr/lib" is unsafe fo
r cross-compilation
| /usr/lib/libQt5Network.so: file not recognized: File format not recognized
```

Remove absolute dir from build definition

---

recipes-devtools/android-tools/android-tools_%.bbappend

0001-Allow-adbd-to-be-ran-as-root.patch contains paths with 'a/', 'b/' prefixes which need to be stripped.
Buildlog snippet:
https://gist.github.com/theappleman/1554e48bc17d32cf88faae3eb94587cd

Fix issue with adbd patch striplevel

---

recipes-qt/qt5/kcalcore_git.bb

Without this dependency, the build task for kcalcore_git was unable to find 'yacc' on my system.

Add missing "bison-native" dependency to kcalcore_git.

---

recipes-nemomobile/usb-moded/usb-moded_git.bb

ADB wasn't working for sturgeon, digging around in the service files made it clear that ADB might not work for all AsteroidOS builds.
When selecting ADB mode from the UI I get this error on my PC:
usb 1-1: new high-speed USB device number 20 using xhci_hcd
**usb 1-1: config 1 has no interfaces?**
usb 1-1: New USB device found, idVendor=18d1, idProduct=0a03, bcdDevice=ff.ff
usb 1-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
usb 1-1: Product: HUAWEI WATCH
usb 1-1: Manufacturer: HUAWEI
This pull request solves the problem at least for sturgeon. Can you maybe test this on other platforms? I will make a pull request for sturgeon if this only affects the sturgeon platform.
Interesting service files are located here:
https://git.sailfishos.org/mer-core/usb-moded/blob/master/systemd …

usb-moded: Fix ADB service not starting properly.

---

recipes-connectivity/bluez5/bluez5/input.conf
recipes-connectivity/bluez5/bluez5_%.bbappend
recipes-multimedia/pulseaudio/pulseaudio/default.pa
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend

This PR includes the needed changes to allow for Bluetooth HID and Audio to work.
A seperate adjustment is needed to patchram.service to fix extreme skipping. That adjustment consists of setting a baudrate. I will make a followup PR for sturgeon with this fix.
You may want to change ControllerMode = le to dual, in main.conf, if a Bluetooth peripheral is not visible when scanning. This is not included in this PR as that change may impact battery life.
We may document this on the asteroidos.org wiki or I think it will be cool if we can change the controller mode in asteroid-settings. Maybe even add the ability to connect Bluetooth peripherals via asteroid-settings :)

Add support for Bluetooth HID and Audio

---

classes/asteroid-image.bbclass
recipes-core/resize-rootfs/resize-rootfs/resize_rootfs
recipes-core/resize-rootfs/resize-rootfs_git.bb

This PR adds a script that uses resize2fs to resize the rootfs to fill the userdata partition when installed on userdata.
When this script is executed on a temporary installation it will exit without using resize2fs.
This PR possibly implements #16.
Please let me know if this PR fulfills the quality requirements to be merged with meta-asteroid.
Couple of uncertainties from my end:
- Is the script located at the proper location(/usr/bin) or should I move this to a reserved location(/var)
- This PR does not incorporate a reboot mechanism. I noticed that Raspbian and Armbian warn that the system should be rebooted when on-line resize is performed.

resize-rootfs: Expand rootfs when installed on userdata.

---

recipes-core/resize-rootfs/resize-rootfs/resize_rootfs
recipes-core/resize-rootfs/resize-rootfs_git.bb

Once again, sorry for not testing this properly...
I have now moved the script contents to the recipe. It previously didn't seem to run the script. But with ALLOW_EMPTY_${PN} = "1" this seems to be solved.

resize-rootfs: Move script contents to recipe.

---

recipes-connectivity/openssh/openssh/0001-Deny-non-fatal-shmget-shmat-shmdt-in-preauth-privsep.patch
recipes-connectivity/openssh/openssh_%.bbappend

It looks like OpenSSL was updated to 1.1.1d from oe-core (https://github.com/openembedded/openembedded-core/commits/warrior). This appears to break OpenSSH with older kernels.
A fix has already been made upstream. This should be included in 8.2 release. I think it will take some time before we get this release in the warrior branch.
Instead of using this patch, we may also freeze the oe-core (https://github.com/AsteroidOS/asteroid/blob/master/prepare-build.sh#L74) to a specific SRCREV. This makes everything less susceptible to bugs in the oe-core branch at the cost of having outdated packages.
This patch will also need to be removed when we inevitably get the OpenSSH 8.2 release in the oe-core repo.
This also fixes https://github.com/AsteroidOS/meta-mtk6580-hybris/issues/8
References: …

openssh: fix login on old kernels with openssl 1.1.1d

---

recipes-graphics/libsdl2/libsdl2/0001-wayland-support-wl_data_device_manager-version-3.patch
recipes-graphics/libsdl2/libsdl2_%.bbappend

OpenGL is enabled in DISTRO_FEATURES. But opengl isn't actually provided by libhybris.
We also need an upstream patch to fix runtime errors with older wayland protocol specs.
This fixes the following runtime issue:
wl_registry@2: error 0: invalid version for global wl_data_device_manager (4): have 1, wanted 3

libsdl2: fix compilation and runtime errors.

---

recipes-nemomobile/ngfd/ngfd-plugin-droid-vibrator/50-droid-vibrator.ini

The ffmemless version uses the clock pattern for alarm events.
This caused alarm.ini to refer to effect = clock. Which does not exist for the non-ffmemless version.
Renaming the alarm event to clock fixes this issue.
This should fix https://github.com/AsteroidOS/meta-wren-hybris/issues/3 and fix https://github.com/AsteroidOS/meta-lenok-hybris/issues/6

ngfd-plugin-droid-vibrator: Rename alarm to clock.

---

classes/asteroid-image.bbclass

As per https://github.com/openembedded/openembedded-core/commit/c7c5f4065c102fde4e11d138fb0b6e25bffe0379#diff-c5130ef47a8c44ef3dc72358e5dd3ed0L1134 the deploy directory for the package index has been changed to a different directory. Using `bitbake package-index` we can manually trigger a package index build for the deploy directory.
This patch adds a copy of the function that is used by `bitbake package-index` just before it builds the rootfs.
This should fix https://github.com/AsteroidOS/meta-bass-hybris/issues/10

asteroid-image: Generate package index when creating image.

---

classes/asteroid-image.bbclass

This patch reduces the rootfs so that there is only about 32MB of free space.
With this patch I think we can finally close https://github.com/AsteroidOS/meta-asteroid/issues/16

rootfs: Reduce free space.

---

classes/asteroid-image.bbclass

In a previous commit I provided a fix for the repository not being generated. However, it seems that I forgot to include the dependency for the `opkg-make-index` tool.
This results in errors during a clean build.
This fixes https://github.com/AsteroidOS/asteroid/issues/115

asteroid-image: package-index depends on opkg-make-index.

---

classes/asteroid-image.bbclass

Some ports require kernel modules to be packaged with rootfs.
This patch fixes sensors not working on sparrow.
Big thanks to @hummlbach for providing help in fixing this issue!
This patch was originally applied to the meta-sparrow platform only. This seems general enough to be included for all platforms. Other platforms swift, anthias and tetra also use kernel modules which likely aren't included in the final image. This may fixes issues on those platforms too, though not tested!
Close this PR if it turns out that this PR has negative effects on other platforms.

linux: Add kernel modules to image.

---

conf/machine/include/hybris-watch.inc

https://github.com/openembedded/openembedded-core/blob/warrior/meta/conf/machine/include/tune-cortexa7.inc#L1 has the default tune: armv7vethf-neon
This results in either tune `armv7vehf-neon` or `armv7vet2hf-neon` based on https://github.com/openembedded/openembedded-core/blob/warrior/meta/conf/machine/include/arm/arch-armv7ve.inc#L84.
I guess it select one of the tunes based on which platform is build first.
Setting the default tune to `armv7vehf-neon` should result in only `armv7vehf-neon`.
This should fix opkg not working with the current nightly build.
Note: My system is still building (has to build everything again :/). Will report when tested.

machine: Set default architecture tune to armv7vehf-neon

---

recipes-core/initrdscripts/initramfs-scripts-android/init.sh

This is used for lenok (and will probably be used for others) to mount the `persist` filesystem and restart the wifi controller, loading the correct MAC address before the real system starts. Can be used for a lot of machine specific things, though.
Everything `init.machine` prints on `stdout` is redirected to `/dev/ttyprintk` - the kernel log.

This allows machines to add a `init.machine` script to initramfs

---

recipes-nemomobile/lipstick/lipstick_git.bb
recipes-nemomobile/timed/timed/0002-Add-wakeup-event-for-use-with-ambient-mode.patch
recipes-nemomobile/timed/timed_git.bb
recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0006-Add-ambient-mode-display-support.patch
recipes-qt/qt5/qt5-qpa-hwcomposer-plugin_git.bb

The PR adds support for an Always on display functionality. Because qt5-qpa-hwcomposer-plugin & timed don't have a repo in the AsteroidOS organization. It may be easier to look in the separate commits for review:
https://github.com/MagneFire/qt5-qpa-hwcomposer-plugin/commit/1c568ba41538408449a77e58357d16bbbb197bf4
https://github.com/MagneFire/timed/commit/28c579dc30a7e5499d68a128ec479f9c064c1dd3
Other PRs that are also needed are:
- https://github.com/AsteroidOS/lipstick/pull/9
- https://github.com/AsteroidOS/asteroid-launcher/pull/42
- https://github.com/AsteroidOS/mce/pull/4
- https://github.com/AsteroidOS/asteroid-settings/pull/25
And for devices I have tuned the ambient mode brightness setting for sturgeon and smelt:
- https://github.com/AsteroidOS/meta-sturgeon-hybris/pull/11
- …

qt5-qpa-hwcomposer-plugin & timed: Add support for ambient mode.

---

recipes-nemomobile/qtdbusextended/qtdbusextended/0001-Use-variant-when-setting-properties.patch
recipes-nemomobile/qtdbusextended/qtdbusextended_git.bb

When setting the volume, shuffle, loop status it would fail with:
error time=1598646695.682396 sender=:1.3 -> destination=:1.12 error_name=org.freedesktop.DBus.Error.UnknownMethod reply_serial=69
string "No such method 'Set' in interface 'org.freedesktop.DBus.Properties' at object path '/org/mpris/MediaPlayer2' (signature 'ssd')"
This is due to qtdbusextended setting the properties using the type and value immediately (double:0.4), while the format variant:type:value(varient:double:0.4) is expected.
This commit fixes this issue by wrapping the type and value in a variant.
It took me quite some time to figure out what was going wrong :cry: 
Some useful things that may be helpful for others are:
- Use dbus-monitor, to look at all dbus messages.
- Use the `dbus-send --print-reply …

qtdbusextended: Fix setting mpris properties.

---

recipes-nemomobile/qtdbusextended/qtdbusextended_git.bb

Oops, somehow it was working on my machine.
Anyway, adding a backslash fixes the recipe parse error.

qtdbusextended: Fix recipe parse error.

---

recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0007-backend-setInteractive-based-on-display-state.patch
recipes-qt/qt5/qt5-qpa-hwcomposer-plugin_git.bb

Appears to fix Always-on-Display on some platforms (wren confirmed.).
Huge thanks to @daniellandau for helping fix this issue!

qt5-qpa-hwcomposer-plugin: Use PowerHAL to setInteractive based on display state.

---

recipes-qt/qt5/qtwayland/0003-xdg-shell-Add-support-for-extended-surfaces.patch
recipes-qt/qt5/qtwayland_git.bbappend

Needed for the custom flags we use in `lipstick`. Without it the back gestures won't work when using the `xdg-shell`.

qtwayland: xdg-shell: Add support for extended surfaces.

---

recipes-asteroid/asteroid-machine-config/asteroid-machine-config_1.0.bb
recipes-asteroid/qml-asteroid/qml-asteroid_git.bb

Adjust recipe to use a `machine.conf` file when it is provided by a meta-*-hybris layer. Otherwise the defaults are assumed.

qml-asteroid: Use a configuration file for device specific settings.

---

recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0008-backend-Don-t-crash-when-power-HAL-doesn-t-exist.patch
recipes-qt/qt5/qt5-qpa-hwcomposer-plugin_git.bb

Some platforms (tetra) don't have a working PowerHAL, Always-on-Display might not work, but this is not a fatal error.

qt5-qpa-hwcomposer-plugin: Don't crash when PowerHAL doesn't work.

---

recipes-qt/qt5/qtlocation_git.bbappend

We only have GeoClue 0.12.99 installed. For some reason Qt still decides that it should use the GeoClue2 plugin.
Removing the plugin fixes this issue.

qtlocation: Remove GeoClue2 plugin.

---

classes/asteroid-image.bbclass
recipes-asteroid/asteroid-package-feed/asteroid-package-feed.bb

This PR adds the ability for other layers to define a set of packages to install in the package feed for use with `opkg`. An example use is like what I've done in the `meta-games` repo: https://github.com/MagneFire/meta-games/blob/community_repo/conf/layer.conf#L13.
A nice thing is that packages won't be build in the package feed when a layer doesn't exist. So it decouples the community packages from the main repos.
Also, because of this added functionality I have removed the creation of the package feed from the `bitbake asteroid-image` command.
So users building AsteroidOS don't actually build the package feed. This however does mean that an adjustment has to be made on the build server such that after a asteroid-image build the `bitbake asteroid-package-feed` command is used to update …

Add support for community repositories

---

recipes-asteroid/asteroid-package-feed/asteroid-package-feed.bb

For some reason only the essential tasks are built to create the ipk.
Using the SSTATETASKS we get the list of all tasks and append that as a dependency for the package feed packages.

asteroid-package-feed: Make sure that all dependencies of tasks are fulfilled

---

recipes-core/libhybris/libhybris/0004-Report-support-for-only-2.0-instead-of-3.0.patch
recipes-qt/qt5/qtwayland/0001-Forces-GLES2-the-dirty-way.patch
recipes-qt/qt5/qtwayland/0002-Revert-most-of-Remove-QWaylandExtendedSurface-from-t.patch
recipes-qt/qt5/qtwayland/0003-xdg-shell-Add-support-for-extended-surfaces.patch

See main PR: https://github.com/AsteroidOS/meta-sturgeon-hybris/pull/16
Additionally, I noticed some warnings with `qtwayland`, refreshing the patches fixes this too.

libhybris: Provide patch to force GLESv2.

---

recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0001-Add-ambient-mode-display-support.patch

hwcomposer versions 1.3 and below don't provide the HWC_POWER_MODE_DOZE_SUSPEND mode, instead they rely on not blanking the display at all.
Further handling of Always-on-Display is handled by PowerHAL (i.e. Writes to sysfs display states).
This change makes it so that all hwcomposers using the backend v11 technically support Always-on-Display mode.
Look https://github.com/AsteroidOS/meta-tetra-hybris/issues/12 for some more background on this specific issue.
Other relevant PR: https://github.com/AsteroidOS/meta-tetra-hybris/pull/14

qt5-qpa-hwcomposer-plugin: Add Ambient mode support for hwcomposer <= 1.3.

---

recipes-asteroid/asteroid-alarmclock/asteroid-alarmclock_git.bb
recipes-asteroid/asteroid-calculator/asteroid-calculator_git.bb
recipes-asteroid/asteroid-calendar/asteroid-calendar_git.bb
recipes-asteroid/asteroid-camera/asteroid-camera_git.bb
recipes-asteroid/asteroid-compass/asteroid-compass_git.bb
recipes-asteroid/asteroid-flashlight/asteroid-flashlight_git.bb
recipes-asteroid/asteroid-hrm/asteroid-hrm_git.bb
recipes-asteroid/asteroid-music/asteroid-music_git.bb
recipes-asteroid/asteroid-settings/asteroid-settings_git.bb
recipes-asteroid/asteroid-stopwatch/asteroid-stopwatch_git.bb
recipes-asteroid/asteroid-timer/asteroid-timer_git.bb
recipes-asteroid/asteroid-weather/asteroid-weather_git.bb
recipes-asteroid/qml-asteroid/asteroid-generate-desktop-native_git.bb
recipes-asteroid/qml-asteroid/qml-asteroid_git.bb
recipes-devtools/cmake/extra-cmake-modules_git.bb
recipes-qt/qt5/qtbase-native_git.bbappend

This is part of the excellent work by @PureTryOut https://github.com/AsteroidOS/qml-asteroid/pull/14!
In order to reduce image space used, the built translation files are removed when they were only used for the .desktop file generation.
This PR does not include the needed changes for asteroid-launcher as the relevant PR (https://github.com/AsteroidOS/asteroid-launcher/pull/49) for that one depends on the removal of statefs: https://github.com/AsteroidOS/meta-asteroid/pull/61
I should mention that even though this work now also checks for runtime QML modules. It fails to find all of them. This currently results into a compile time warning, that is only visible when looking at the configure logs.

Port to CMake

---

recipes-graphics/ttf-fonts/ttf-asteroid-fonts/69-emoji.conf
recipes-graphics/ttf-fonts/ttf-asteroid-fonts_git.bb

Replace the current emoji fonts with the Twitter emoji fonts. They suit better to the _flat_ design that AsteroidOS uses.
| Before | After |
|----------|--------|
| ![Screenshot_20211125_191126](https://user-images.githubusercontent.com/7857908/143492953-12c91a04-3562-4389-aced-c2d20263c4c0.jpg) | ![Screenshot_20211125_202253](https://user-images.githubusercontent.com/7857908/143492955-4ecde500-0755-4584-b33e-8dfc524597e5.jpg) |
Relevant other PR: https://github.com/AsteroidOS/asteroid-fonts/pull/2

ttf-asteroid-fonts: Use Twemoji emoji fonts.

---

recipes-asteroid/asteroid-btsyncd/asteroid-btsyncd_git.bb

This work depends on: https://github.com/AsteroidOS/asteroid-btsyncd/pull/20

asteroid-btsyncd: Port to CMake.

---

conf/distro/asteroid.conf

Fix bug #80 by replacing i586 with core2-32.  This fixes the
problem of missing i586 directory in generated nightly ipks
and provides the qemux86 target with a correct path for opkg.

Replace i586 with core2-32

---

recipes-asteroid/asteroid-launcher/asteroid-launcher/asteroid-launcher.service
recipes-core/initrdscripts/initramfs-scripts-android/init.sh
recipes-core/psplash/files/0002-psplash-Allow-for-moving-the-named-pipe.patch
recipes-core/psplash/psplash_git.bbappend

This adds the necessary parts to allow the `ceres` user to stop `psplash`.
`psplash` exposes a `/run/psplash_fifo` (named pipe) in the ramdisk. This can be used to quit `psplash` by means of the command: `echo QUIT > /run/psplash_fifo`. This is however limited to the ramdisk. We need some way to transfer this named pipe to the new root. So that we can properly quit `psplash`.
This is achieved by adding a `FIFO` command that takes a new root. This allows for displaying the boot logo while transferring control to the new root.
This fixes https://github.com/AsteroidOS/asteroid/issues/180 and possibly https://github.com/AsteroidOS/asteroid/issues/191 too (needs a bit more testing).

Close psplash before starting asteroid-launcher.

---

recipes-core/libhybris/libhybris_git.bbappend

libhybris uses pkgconfig to get the prefix for the wayland-scanner. Unfortunally this causes it to use: /usr/bin/wayland-scanner (host tool!).
We don't want this to happen, instead patch it so that it uses wayland-scanner from the sysroot.
~Additionally move the applying of the other two patches to here too. It should not be needed to apply this separately for every watch. Instead a watch can just clear the patches required for a 'new' libhybris build.~ Bad choice because it's not easy to clear all patches used!
I'll need to undo the above

libhybris: Fix compilation.

---

recipes-core/initrdscripts/initramfs-scripts-android/init.sh

It is not used for anything and causes issues with mounting the filesystem of meta-narwhal-hybris.

Remove 'nodelalloc' from init.sh

---

recipes-nemomobile/geoclue-providers/geoclue-provider-hybris_git.bb

Fixes: `Project ERROR: libhardware development package not found`
This issue occurred when building the toolchain.

geoclue-provider-hybris: Inherit pkgconfig to fix build issue.

---

recipes-core/firmwared/firmwared/firmwared.service

Android/WearOS often provides a dedicated partition for firmware files.
This is generally mounted under `/firmware`.
The initrdscripts already provides the logic to mount the firmware partition via the `firmware_partition` variable.
This is also need by https://github.com/AsteroidOS/meta-smartwatch/pull/95 as it copies the touchscreen firmware files to `/firmware`.

firmwared: Add /firmware/image to the firmware search path.

---

recipes-core/lcd-tools/lcd-tools.bb

See relevant PR: https://github.com/AsteroidOS/lcd-tools/pull/2

lcd-tools: Change install path and dependencies to support 24 hour mode.

---

recipes-nemomobile/libaccounts/libaccounts-qt5_git.bb

This is one of the steps required for an update to a working calendar
import for the watch.

Update libaccounts-qt to version 1.16

---

recipes-devtools/cmake/extra-cmake-modules_git.bb

This is done as a first step in updating nemo-qml-plugin-calendar, and
is also useful for updating other recipes in the future.

Update to newer version of extra-cmake-modules

---

recipes-qt/qt5/kcalendarcore_git.bb

To improve calendar handling code (see the feature request
https://github.com/AsteroidOS/asteroid/issues/221), it is useful to
update mkcal and nemo-qml-plugin-calendar to more recent versions. This
is a step toward making that possible.

Add kcalendarcore to the watch

---

recipes-asteroid/asteroid-machine-config/asteroid-machine-config_1.0.bb
recipes-core/os-release/os-release.bbappend

This adds several useful fields to /etc/os-release so that, for
instance, on sturgeon, the new values look like this:
BUILD_ID="20220726172548"
DEFAULT_HOSTNAME="sturgeon"
LOGO=logo-asteroidos
HOME_URL="https://asteroidos.org/"
These fields, their encodings and meanings are documented here:
https://www.freedesktop.org/software/systemd/man/os-release.html

Add more information to os-release

---

recipes-nemomobile/nemo-qml-plugins/nemo-qml-plugin-systemsettings/0006-Add-file-to-the-places-searched-for-a-serial-number.patch
recipes-nemomobile/nemo-qml-plugins/nemo-qml-plugin-systemsettings_git.bb

This patches nemo-qml-plugin-systemsettings to allow that plugin to
correctly fetch the serial number for AsteroidOS and parallels a change
already made to upstream in commit
96b6ae08c6ce47dbcb6625227905eda21383e2bc.

Add the usb-moded file location for serial number

---

recipes-asteroid/asteroid-compass/asteroid-compass_git.bb

Since the recent redesign we now add a calibration text which can be translated.

asteroid-compass: Keep translation files.

---

recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0001-Add-ambient-mode-display-support.patch
recipes-qt/qt5/qt5-qpa-hwcomposer-plugin_git.bb

This adds support for Always-on-Display on hwc2 devices (Android 9+).
Additionally it adds support for the use of the PowerHAL on older hwc versions.
Signed-off-by: Darrel Griët <dgriet@gmail.com>

qt5-qpa-hwcomposer-plugin: Add Always-on-Display support for hwc2.

---

recipes-qt/qt5/qtbase_git.bbappend

By default, qtbase 5 attempts to load libssl-1_1 and libcrypto-1_1 as can be seen in this function: https://github.com/qt/qtbase/blob/v5.15.4-lts-lgpl/src/network/ssl/qsslsocket_openssl_symbols.cpp#L670
The problem is that those versions are old and don't handle ssl very well.  This Javascript code was being called in response to a button press in QML, but the request failed every time.
function getWeatherForecast(lat, lon, apikey) {
const xhttp = new XMLHttpRequest();
xhttp.onreadystatechange = function() {
if (xhttp.readyState == XMLHttpRequest.DONE && xhttp.status == 200) {
updateForecast(xhttp.responseText.toString());
} else {
console.log("readystate: ", xhttp.readyState);
console.log("HTTP status: ", xhttp.status);
}
};
var url = "https://asteroidos.org/CNAME";
console.log("url: ", …

Fix OPENSSL_LINKING_MODE in qtbase

---

recipes-nemomobile/geoclue-providers/files/0001-pri-Fix-host-contamination-path-issue.patch
recipes-nemomobile/geoclue-providers/geoclue-provider-hybris-binder_git.bb
recipes-nemomobile/geoclue-providers/geoclue-provider-hybris-hal_git.bb
recipes-nemomobile/geoclue-providers/geoclue-provider-hybris.inc

From now on provide a HAL (gps.x.so) and a binder (/dev/hwbinder) version of the `geoclue-provider-hybris`.
Before merging this requires changes to https://github.com/AsteroidOS/meta-smartwatch which I'll create a PR for if this is all good.
Additionally, this work depends on https://github.com/AsteroidOS/meta-asteroid/pull/112.

geoclue-provider-hybris: Bump SRCREV to 0.2.35 and split recipe.

---

recipes-devtools/gdb/gdb_%.bbappend

Enable some features within GDB to improve debugging. Enabling LZMA support fixes issues like:
```
warning: Cannot parse .gnu_debugdata section; LZMA support was disabled at compile time
```
Signed-off-by: Darrel Griët <dgriet@gmail.com>

gdb: Enable LZMA support.

---

recipes-android/tls-padding/tls-padding.bb
recipes-android/tls-padding/tls-padding/tls-padding.conf
recipes-test/tls-regression-test/tls-regression-test.bb

We've seen multiple instances where stranges crashes would occur. The cause could be related to thread local storage conflicts between Android libraries (via libhybris) and LibC. This adds a recipe to check for those conflicts and a workaround library to pad the TLS space.
Signed-off-by: Darrel Griët <dgriet@gmail.com>

Add Thread-Local Storage tests and workaround.

---

recipes-nemomobile/libdbusaccess/libdbusaccess_git.bb
recipes-nemomobile/libnci/libncicore/0001-Makefile-Allow-for-CC-to-be-overridden.patch
recipes-nemomobile/libnci/libncicore_git.bb
recipes-nemomobile/libnci/libnciplugin/0001-Makefile-Allow-for-CC-to-be-overridden.patch
recipes-nemomobile/libnci/libnciplugin_git.bb
recipes-nemomobile/mce/libmce-glib_git.bb
recipes-nemomobile/nfcd/nfcd-binder-plugin/0001-Makefile-Allow-for-CC-to-be-overridden.patch
recipes-nemomobile/nfcd/nfcd-binder-plugin_git.bb
recipes-nemomobile/nfcd/nfcd-mce-plugin_git.bb
recipes-nemomobile/nfcd/nfcd/0001-Makefile-Allow-for-CC-to-be-overridden.patch
recipes-nemomobile/nfcd/nfcd/0002-Makefile-Allow-for-INSTALL_SYSTEMD_DIR-to-be-overrid.patch
recipes-nemomobile/nfcd/nfcd_git.bb

This PR adds the packages to support NFC. It has been testen on `catfish` and `beluga`.
It does not work on `catfish` because of https://github.com/mer-hybris/libncicore/issues/21 (A ST21NFCD which is a  NCI 2.0 chip).
It appears to work fine on `beluga`.
The packages are not installed by default as no app within AsteroidOS would have a direct benefit from it, we could reconsider this in the future of course.

Add packages for NFC support.

---

recipes-android/swclock-offset/swclock-offset/swclock-offset.service
recipes-android/swclock-offset/swclock-offset_git.bb

This PR adds the recipe for swclock-offset (https://gitlab.com/postmarketOS/swclock-offset).
It's purpose is to restore the system time from a non-writeable RTC by using a cached file. Which appears to be an issue on some Qualcomm based watches.
I've also made a PR upstream, but we can use this until that one is merged:
https://gitlab.com/postmarketOS/swclock-offset/-/merge_requests/3
Thanks for @dodoradio for his initial work on this!

Add swclock-offset recipe.

---

recipes-nemomobile/geoclue-providers/files/0002-hal-Handle-not-being-able-to-set-the-SUPL-server.patch
recipes-nemomobile/geoclue-providers/geoclue-provider-hybris.inc

https://github.com/mer-hybris/geoclue-providers-hybris/commit/e982cf94047993e5868d44307f4a38f1b89500ea added support for overriding/setting the SUPL server. This could however lead to a crash when AGPS isn't actually available. Handle this by returning an error instead of crashing.
Signed-off-by: Darrel Griët <dgriet@gmail.com>
This patch will be dropped when the upstream PR is merged: https://github.com/mer-hybris/geoclue-providers-hybris/pull/44

geoclue-provider-hybris: hal: Handle not being able to set the SUPL server.

---

classes/asteroid-image.bbclass
recipes-qt/packagegroups/nativesdk-packagegroup-qt5-toolchain-host.bbappend

This allows for building asteroid-btsyncd, asteroid-launcher etc. with SDKs generated by Yocto via calls like:
bitbake -c populate_sdk asteroid-image

Enable proper qmake, Qt Linguist, moc/uic/rcc, and CMake support in SDKs

---

recipes-qt/packagegroups/packagegroup-qt5-toolchain-target.bbappend

The previous version of SDK did not contain the CLI11 header-only library necessary to build lcd-tools

Add cli11 to SDK for building lcd_tools

---

conf/machine/include/hybris-watch.inc

Given that the hybris-watch.inc file makes no mention of being architecture-specific, it does not make sense for it to be setting an armv7-specific processor tune. This, along with [the corresponding commit in meta-smartwatch](https://github.com/AsteroidOS/meta-smartwatch/pull/158), moves this parameter to machine-specific conf files, which should allow hybris-watch.inc to be used by watches with processor architectures other than armv7, without unnecessarily overriding the defaulttune. The PR to meta-smartwatch should be merged first.

Remove default armv7 tune.

---

recipes-qt/qt5/qttools/0001-Build-kmap2qmap-tool.patch

input_support-private is not available when building the SDK. To workaround build issues disable compiling kmap2qmap whenever the input_support-private dependency isn't available.

qttools: Compile kmap2qmap when available.

---

recipes-connectivity/connman/connman/connman-dbus.conf

This fixes a bug that prevented the ceres user from being able to use introspection of connman which contributed to not being able to use libconnman-qt5 as used in the asteroid-weather-glow watchface.  This is the other part of the fix for https://github.com/AsteroidOS/asteroid/issues/243

Allow ceres user to use dbus introspection

---

recipes-core/initrdscripts/initramfs-scripts-android/init.sh

The sdcard partition can be on another block device and there's no point hard-coding a device when we have $sdcard_partition at our disposal anyway.

initramfs-scripts-android: Wait on the sdcard partition rather than mmcblk0

---

recipes-core/lcd-tools/lcd-tools.bb

koi has now been added as to meta-smartwatch. support for it has existed in lcd-tools for a while now, so now seems like an appropriate time to declare it compatible.

lcd-tools: remove `COMPATIBLE_MACHINE`

---

recipes-core/lcd-tools/lcd-tools.bb

https://github.com/AsteroidOS/meta-asteroid/commit/a75a35628a1d9d858ef687c7829dc6f5b4d4fc8c was supposed to remove this line but didn't, this rectifies this.

lcd-tools: Actually remove the `COMPATIBLE_MACHINE` line.

---

recipes-qt/qt5/qttools/0002-kmap2qmap-Map-MenuKB-key.patch
recipes-qt/qt5/qttools_git.bbappend

This adds support for mapping the MenuKB key (keycode 139).
It essentially fixes the second button on `catfish`

qttools: Add support for mapping the MenuKB key.

---

recipes-graphics/ttf-fonts/ttf-asteroid-fonts_git.bb

Stock images are now shipped with more fonts (https://github.com/AsteroidOS/asteroid-fonts/commit/341a7ac195ed953c0843b72cc98db9d539a5c993), this resulted into an update of the license text used in the readme.
Currently, `Arkhip` uses a license that's not available in the SPDX License list. We might have to alter this at some point as well.

ttf-asteroid-fonts: Fix license checksum.

---

classes/asteroid-image.bbclass
conf/distro/asteroid.conf

This PR is a prerequisite to being able to apply https://github.com/AsteroidOS/asteroid-settings/pull/63 by adding `polkit` and the polkit rule that allows the `ceres` user to change the time, date, and timezone.

Add polkit to allow time change

---

recipes-android/android-init/android-init_1.0.bb

https://github.com/AsteroidOS/meta-asteroid/commit/06dc67571b21cb2f6ec3e2924cd06a9b354e073d introduced a change where the android-init service file would install to a location using the Yocto system package variables. This however turned out to be the incorrect variable.
The `systemd_unitdir` variable is not the correct path to install systemd unit files (it represents the /lib/systemd/ path).
Instead use `systemd_system_unitdir` variable to install the systemd unit file into the correct path (/lib/systemd/system/).

android-init: Fix install path of the android-init.service.

---

recipes-graphics/ttf-fonts/ttf-asteroid-fonts_git.bb

Stock images are now shipped with more fonts as part of a new stock watchface (https://github.com/AsteroidOS/asteroid-fonts/pull/16), this resulted into an update of the license text used in the readme.

ttf-asteroid-fonts: Update license checksum.

---

recipes-asteroid/asteroid-virtualkeyboard/asteroid-virtualkeyboard_git.bb

This is a follow-up on https://github.com/AsteroidOS/meta-asteroid-community/pull/17. The recipe was never added to `meta-asteroid`.

Add asteroid-virtualkeyboard recipe.

---

recipes-core/initrdscripts/initramfs-scripts-android/init.sh

The userdata partition is partially encrypted on newer watches. In most cases the root of the userdata partition isn't encrypted, but everything in the `media` folder is encrypted. This adds the root of the userdata partition as a valid location for the ext4, but it means that the ext4 image needs to be pushed externally (i.e. on first boot of the AsteroidOS kernel).

initramfs-scripts-android: Add userdata root to the ext4 search path.

---

recipes-asteroid/asteroid-alarmclock/asteroid-alarmclock_git.bb
recipes-asteroid/asteroid-calculator/asteroid-calculator_git.bb
recipes-asteroid/asteroid-calendar/asteroid-calendar_git.bb
recipes-asteroid/asteroid-camera/asteroid-camera_git.bb
recipes-asteroid/asteroid-compass/asteroid-compass_git.bb
recipes-asteroid/asteroid-diamonds/asteroid-diamonds_git.bb
recipes-asteroid/asteroid-flashlight/asteroid-flashlight_git.bb
recipes-asteroid/asteroid-gps/asteroid-gps_git.bb
recipes-asteroid/asteroid-hrm/asteroid-hrm_git.bb
recipes-asteroid/asteroid-music/asteroid-music_git.bb
recipes-asteroid/asteroid-settings/asteroid-settings_git.bb
recipes-asteroid/asteroid-stopwatch/asteroid-stopwatch_git.bb
recipes-asteroid/asteroid-timer/asteroid-timer_git.bb
recipes-asteroid/asteroid-weather/asteroid-weather_git.bb

AsteroidOS applications previously installed a library to `/usr/bin`. This was due to legacy reasons. Recently, this has been solved by instead providing a script that executes the `invoker` with the proper `/usr/lib/asteroid-<app>.so`.
Relevant other PRs:
- https://github.com/AsteroidOS/qml-asteroid/pull/45
- https://github.com/AsteroidOS/asteroid-gps-test/pull/4
- https://github.com/AsteroidOS/asteroid-weather/pull/20
- https://github.com/AsteroidOS/asteroid-timer/pull/17
- https://github.com/AsteroidOS/asteroid-stopwatch/pull/11
- https://github.com/AsteroidOS/asteroid-settings/pull/86
- https://github.com/AsteroidOS/asteroid-music/pull/24
- https://github.com/AsteroidOS/asteroid-hrm/pull/11
- https://github.com/AsteroidOS/asteroid-helloworld/pull/8
- …

asteroid-apps: Install library files.

---

recipes-devtools/rust/rust-llvm/0003-Add-necessary-include-file.patch
recipes-devtools/rust/rust-llvm_%.bbappend

This adds a patch to add a missing include to allow rust to compile cleanly with newer versions of gcc.

Add patch to allow clean compile

---

recipes-asteroid/asteroid-apps/asteroid-settings_git.bb
recipes-asteroid/asteroid-apps/files/30-org.freedesktop.login1.rules

This adds a rule to allow the ceres user to reboot using D-Bus.  This is needed for an upcoming pull request for asteroid-settings to add the capability of rebooting to the bootloader.

Add polkit rule to allow ceres user to reboot

---

recipes-asteroid/asteroid-apps/polkit-ceres-rule-reboot.bb

This adds the missing polkit install rule.  Thanks to eLtMosen for discovering this omission.

Add file to install polkit rule

---

recipes-asteroid/asteroid-launcher/asteroid-launcher-configs_git.bb

https://github.com/AsteroidOS/meta-asteroid/pull/133 split the asteroid-launcher recipe which resulted in a copying error where `kms-qemu.conf` was installed. But this file doesn't actually exist, instead `kms-qemu.json` should've been installed.
This rectifies this issue.

asteroid-launcher: Fix packaging issue for qemux86.

---

recipes-android/android/android.inc
recipes-android/android/android_armv7-oreo.bb
recipes-android/android/android_armv7-pie32.bb
recipes-android/android/android_armv7-pie64.bb

Provides a generic Android Oreo libhybris recipe instead of polluting the `meta-smartwatch` repo with he same `SRCREV`. This is the same one used by the `koi` port. Which contains some additional fixes to avoid TLS region conflicts with updated versions of libhybris.
Additionally, this changes the naming of the `msm8909+pie` and `msm8909w+pie` recipes as they are both compatible with `msm8909w`. The only difference is that one is targeting a 32-bit binder while the other targets a 64-bit binder.
Reason for this PR still being a draft is because I need to test if this works on the watches I own.

Provide a generic Android O patched libaries and fix Android Pie inconsistency.

---

recipes-extended/timezone/tzdata.bbappend

This builds and installs tzdata.zi.
`timedated` attempts to load `tzdata.zi` which contains the linked regions as well. Currently this fails as this file doesn't exist. As a fallback it loads `zone1970.tab` instead. `zone1970.tab` does not contain the linked timezones. [^1]
This fixes an issue where linked timezones[^2] would not be shown in the ListTimezones DBus method.
[^1]: https://github.com/systemd/systemd/blob/581427bd658c585287a7f3db04eabdce922d9d0e/src/basic/time-util.c#L1443
[^2]: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List

tzdata: Install tzdata.zi.

---

recipes-core/lcd-tools/lcd-tools.bb

this is needed for https://github.com/AsteroidOS/lcd-tools/pull/7 to work

add the new session-restart service needed for settings restore to work

---

recipes-nemomobile/mce/mce/0007-powerkey-Also-suspend-on-palm-reports.patch

The initial code was based on powerkey events.
While this works great, it also meant that the display would be turned on whenever on a palm event. This can occur when the touchscreen interface isn't suspended.
This fixes https://github.com/AsteroidOS/meta-smartwatch/issues/202.

mce: Don't wake screen on palm event.

---

classes/asteroid-image.bbclass

The "metadata_csum" feature changed in an incompatible fashion since the Linux 3.* kernel we use on `sparrow`, for example. This means that loop-mounting the ext4 on a modern Linux system and modifying it will result in a filesystem image that cannot be mounted by `sparrow`'s kernel.
The error message in question is:
```
[  156.079616](CPU:0-pid:235:dmesg) JBD2: Unrecognised features on journal
[  156.079639](CPU:0-pid:235:dmesg) EXT4-fs (mmcblk0p29): error loading journal
```
Marked as draft until I've actually built and tested this on `sparrow`. (I've tested on `beluga` and the `tune2fs -l` output looks okay...)

build ext4 images without ext4's metadata_csum feature

---

recipes-android/brcm-patchram-plus/brcm-patchram-plus/patchram.service
recipes-android/brcm-patchram-plus/brcm-patchram-plus_git.bbappend

The default service doesn't offer anything, it isn't useful on its own. Remove it such that build issues may become clear sooner.
This should fix an issue where the default patchram service is installed on the current nightlies.
This fixes: https://github.com/AsteroidOS/meta-smartwatch/issues/204

brcm-patchram-plus: Remove default service.

---

classes/abootimg.bbclass
classes/mkboot.bbclass
classes/mkbootimg.bbclass

This should fix the recent device bricks seen. The underlying problem was identified and described by @FlorentRevest, this is merely an attempt to translate his observations into a PR.
This means you will not be able to install a new kernel with `opkg` without also invoking fastboot. OTOH, that never worked reliably.
Some of the removed code was dodgy, and most likely caused https://github.com/AsteroidOS/meta-asteroid/issues/175
Further code should be removed but this will happen in a separate PR; this should fix the bricking issue and remove the kernel-update functionality, creating a consistently empty package for `linux-$machine-image` is less of a priority.
Fixes https://github.com/AsteroidOS/meta-asteroid/issues/175.

Remove pkg_postinst_ontarget rule for kernel images.

---

recipes-android/wifi-enabler/wifi-enabler/wifi-enabler.service
recipes-android/wifi-enabler/wifi-enabler_1.0.bb

Some Qualcomm based watches need additional steps to enable WiFi. Ideally this service should be added to the Android init.rc but this does not appear to work since the commands are executed too soon in the boot process.
This provides a systemd service such that WiFi is enabled later in the boot process.

Add wifi-enabler recipe.

---

recipes-nemomobile/nfcd/nfcd_git.bb

NFC seems to cause issues on multiple watches.
On `beluga` it causes for a screen flickering issues on the sides.
On `ray` it causes for random horizontal lines to appear as well as ghost touchscreen presses.
As there's currently little use of NFC disable the service from starting to workaround these issues.
This cause of this issue was first discovered by @argosphil.

nfcd: Don't autostart service.

---

recipes-core/image/asteroid-image-dev.bb

These commits remove dbg-pkgs dev-pkgs to reduce image size, and add htop, bash, and extra Bluetooth tools, which are useful for development and debugging. To quote the first commit's message:
dbg-pkgs and dev-pkgs add ALL dbg and dev packages to the image. The
result is too large for some watches. And, in particular, adding dev
packages to the rootfs of a smartwatch is of very questionable use,
since this is usually done when development tools such as make, cmake,
gcc etc. are to be run on the target itself. This is unlikely to be
done on a smartwatch.

Changes to asteroid-image-dev

---

classes/asteroid-image.bbclass
recipes-devtools/android-simg2img/android-simg2img_git.bb

Previously this was only available for `tetra` since the bootloader didn't support specific chunk types.
But it seems that this is also needed for `pike` when using a real install. Hence import the recipe in `meta-asteroid` and use a global variable to enable sparse image generation.
Other relevant PR: https://github.com/AsteroidOS/meta-smartwatch/pull/238

Add sparse image generation support

---

recipes-core/qrtr/qrtr/0001-Makefile-Allow-for-prefix-override.patch
recipes-core/qrtr/qrtr_git.bb

Adds the userspace Qualcomm IPC router needed for booting the modem on `hoki`.

Add qrtr recipe

---

conf/machine/include/hybris-watch.inc
recipes-asteroid/asteroid-launcher/asteroid-launcher-configs/default.conf
recipes-asteroid/asteroid-launcher/asteroid-launcher/asteroid-launcher-precondition
recipes-asteroid/asteroid-launcher/asteroid-launcher/asteroid-launcher-precondition-hybris
recipes-asteroid/asteroid-launcher/asteroid-launcher_git.bb
recipes-core/systemd/systemd_%.bbappend
recipes-multimedia/pulseaudio/pulseaudio_%.bbappend
recipes-nemomobile/sensorfw/sensorfw.inc
recipes-qt/qt5/qtbase_git.bbappend
recipes-qt/qt5/qtscenegraph-adaptation_git.bb

Some components in AsteroidOS unconditionally depend on libhybris, and many default configs assume a hybris-based device. This PR breaks out these dependencies, paving the way for easily supporting devices running mainline without Android drivers.
Changes to meta-smartwatch are not required. 
I have tested these changes on catfish and they seem to work fine there, but more testing on other watches is appreciated, given how broad the changes are.

Remove unconditional hybris dependencies

---

conf/distro/asteroid.conf

This adds several missing archs to the PACKAGE_FEED_ARCHS variable.  The problem was noted in Matrix chat by user @asozcan who was attempting to update a ray watch using opkg and noted that no ray packages were being downloaded.  Confirming this, it was also noticed that a number of other architectures were also missing.  The ones that were added in this patch are:  beluga catfish firefish harmony hoki inharmony koi minnow mooneye narwhal nemo pike ray skipjack smelt triggerfish
Fixes #191

Add missing architectures to PACKAGE_FEED_ARCHS

---

recipes-qt/qt5/qt5-qpa-hwcomposer-plugin/0001-Add-ambient-mode-display-support.patch

If the display fails to be validated the `QPA_HWC2_FORCE_DOZE_UPDATE` environment variable can be used to temporarily switch the display to on mode.

qt5-qpa-hwcomposer-plugin: Provide workaround for doze mode validation errors

---

recipes-android/swclock-offset/swclock-offset_git.bb

Upstream now also uses /usr. So we don't need to manually state that it needs to be installed there.
Additionally OpenRC and systemd services files are always installed, so we need to remove the OpenRC files manually to fix packaging issues.
This adjusts the recipe to work with these MRs:
- https://gitlab.com/postmarketOS/swclock-offset/-/merge_requests/4
- https://gitlab.com/postmarketOS/swclock-offset/-/merge_requests/5

swclock-offset: Bump SRCREV

---

recipes-nemomobile/usb-moded/usb-moded_git.bb

Upstream changed the ConditionPathExists to use a different path as it's more suitable for build time files. [^1]
Adjust the recipe to create the file on this location similarly to how upstream achieves this. [^2]
Draft PR because this still needs to be tested.
This potentially fixes: https://github.com/AsteroidOS/meta-smartwatch/issues/253
[^1]: https://github.com/openembedded/meta-openembedded/commit/3309a9d4dde1b8cbab60322ec24e121330e23cea
[^2]: https://github.com/openembedded/meta-openembedded/commit/145ae5af9ef45f566f07751a2c2ea6c224e71a24

usb-moded: Create flag file /etc/usb-debugging-enabled

---

recipes-nemomobile/ngfd/ngfd_git.bb

This includes a crash fix for the ffmemless plugin(https://github.com/sailfishos/ngfd/commit/80d356b1c410954c756d3f2cc783a4608e0122b9).
This fixes ngfd from crashing when the alarm fires on `hoki`.

ngfd: Bump SRCREV

---

classes/asteroid-image.bbclass
classes/asteroid-users.bbclass
recipes-asteroid/supported-languages/supported-languages_git.bb
recipes-core/bluetooth-rfkill-event/bluetooth-rfkill-event/0005-Use-strlcpy-instead-of-snprintf-for-string-copy.patch
recipes-core/bluetooth-rfkill-event/bluetooth-rfkill-event_git.bb
recipes-graphics/ttf-fonts/ttf-asteroid-fonts_git.bb
recipes-navigation/geoclue/files/0001-Remove-hardcoded-CFLAGS-that-collide-with-Yocto-OE-C.patch
recipes-navigation/geoclue/geoclue_0.12.99.bb
recipes-nemomobile/dsme/dsme/0002-Fix-and-improve-alarm-time-serialization.patch
recipes-nemomobile/dsme/dsme_git.bb
recipes-nemomobile/lipstick/lipstick_git.bb
recipes-nemomobile/timed/timed_git.bb

These commits introduce fixes for build errors that happen when -Werror is used during compilation. Until now, some rather ugly workarounds were being used that were fragile, for example, by using sed to remove "-Werror" from build scripts. The fixes here patch the code that causes -Werror to trigger build errors, making such hacks unnecessary.
These commits also rework how users and groups are configured. They introduce a new bbclass where AsteroidOS specific users and groups are created centrally. This removes the need for the "host-user-contaminated" `INSANE_SKIP`, and also uses named constants instead of hardcoded UIDs for the ceres user and group.

Several fixes for build errors as well as refactoring of how users and groups are handled

---

recipes-navigation/geoclue/geoclue_0.12.99.bb

This fixes the postinstall step required with geoclue by adding gsettings to the inherited classes.  That class automatically performs the step of compiling the schemas using glib-compile-schemas and also adds the /usr/share/glib-2.0/schemas to the FILES variable for the project, which is why it was removed from this file.
The gsettings also has a postinstrm step that recompiles the schemas after the package is removed.
This fixes https://github.com/AsteroidOS/asteroid/issues/304

Fix geoclue postinstall

---

recipes-devtools/python/python3-pyqt5_%.bbappend

This allows us to build the python3-pyqt5 recipe without having to add QtWidgets or mesa.  It also applies some patches from ST to fix yocto build errors.
This fixes https://github.com/AsteroidOS/asteroid/issues/227 and https://github.com/AsteroidOS/asteroid/issues/98

Add patch for python3-pyqt5 recipe
